### ISSUE TITLE
how to setup the env?

### ISSUE THREAD

**Issue by PhilMata** [ShadovvBeast/TalkGPT#1]
I was wondering how to set the .env file because I've tried to use the valid email and password and providing the ATH.TOKEN but nothing i get the error invali Token

**Comment by Ruitjes** [comment]
> I was wondering how to set the .env file because I've tried to use the valid email and password and providing the ATH.TOKEN but nothing i get the error invali Token

Same thing, I guess its already outdated.

**Comment by ShadovvBeast** [comment]
It's not outdates and still works, what exactly did you have trouble with?
We don't use dotenv, so the env vars are actual environment variables, not defined in a .env file (in the backend)
in the frontend, there is a .env file, that has the VITE_BACKEND_URL var(should be defined as http://localhost:3000 if you are running locally with the default settings)
