### ISSUE TITLE
Narration of text in Russian stops abruptly

### ISSUE THREAD

**Issue by Anixx** [ShadovvBeast/TalkGPT#3]
The narration of the text received from ChatGPT in Russian stops before the end of the text. Even if that text was received from ChatGPT in text form completely.

**Comment by ShadovvBeast** [comment]
Could you provide a way to reproduce this?

**Comment by Anixx** [comment]
This happens with any sufficiently large output in Russian, sometimes even the words are unfinished. This issue is common and was noticed by all Russian-language ChatGPT observers.

Possibly the devs did not account that Cyrillic letters take 3 bytes in Unicode unlike Latin which takes 1 byte, or due to time limitation, as output in Russian is slower (again possinly because the delay between characters is set in bytes per second).

**Comment by ShadovvBeast** [comment]
Seems to be a frontend issue.
Looks like the browser's speech synthesis (window.speechSynthesis) doesn't support Russian, if you want to contribute and add a different speech synthesis method that does support it, feel free to open a PR :)
