### ISSUE TITLE
infinite loading response with frontend

### ISSUE THREAD

**Issue by DamascusGit** [ShadovvBeast/TalkGPT#5]
I can't seem to use "yarn start" in the final step after "cd frontend" in the second terminal. i saw it wasn't actually in the scripts for the frontend package.json.

Instead, I have to use "yarn dev" or "yarn preview", and the frontend loads up + the audio transcription works great, but I never get a response, just an infinite loading graphic.

any idea on a solution? 

if it makes any difference, the ports are different when i run preview/dev vs the session server port from the main directory

here's the issue being thrown for me when i inspect element on the frontend localhost:

VM34:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by ShadovvBeast** [comment]
Are you running both the server and the client? you need to run them both in 2 terminals
Have you populated all the required env vars? I recommend that for the server, you populate the CHATGPT_SESSION_TOKEN env var, so the pawan version will be used, it seems to be the most stable right now

**Comment by DamascusGit** [comment]
Yes, I run them in two different terminals in vscode. I set the env variable for Pawan version, otherwise server doesn’t run. 

Server goes up, client goes up, audio transcription works, then stuck on the little loading icon indefinitely.

still an issue getting a response back. No responses. Just one way

**Comment by ShadovvBeast** [comment]
i'm not able to recreate this, what OS are you using? i've tested using Windows 10 and using Ubuntu Linux and both seem to work fine.
Could you provide a way to recreate this?

**Comment by ShadovvBeast** [comment]
Seems to be working fine, especially with the new version of Pawan's api, make sure the CHATGPT_SESSION_TOKEN is configured correctly (not through a .env file, it needs to be an actual env var)
