### ISSUE TITLE
Response from chatGPT API

### ISSUE THREAD

**Issue by markNZed** [ShadovvBeast/TalkGPT#8]
Hi, with recent changes I think this needs to use resp.answer.text if the server is using process.env.OPENAI_API_KEY
https://github.com/ShadovvBeast/TalkGPT/blob/17e38f29c6b16f74cde05af49b303b30da85e797/frontend/src/App.tsx#L20

**Comment by ShadovvBeast** [comment]
Fixed in the latest version, thanks
